server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 127.0.0.1
    username: leyou
    password: leyou
    virtual-host: /leyou
  redis:
    host: 127.0.0.1
ly:
  sms:
    accessKeyId:  # 你自己的accessKeyId
    accessKeySecret:  # 你自己的AccessKeySecret
    signName: 项目短信测试  # 签名名称
    verifyCodeTemplate: SMS_186579606 # 模板名称
